services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: scicat_sso_keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      default:
        aliases:
          - keycloak.local

# === Local SciCat backend from source ===
  mongodb:
    image: mongo:latest
    ports:
          - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami"
  backend:
    build:
      context: ../backend
      target: dev
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - /home/jl/Work/cat/backend:/home/node/app
      - /home/jl/Work/cat/backend/test/config/functionalAccounts.json:/home/node/app/functionalAccounts.json
      - /home/node/app/node_modules
      - /home/node/app/dist
    environment:
      MONGODB_URI: mongodb://mongodb:27017/scicat
      EXPRESS_SESSION_SECRET: a_scicat_secret
      JWT_SECRET: a_scicat_secret
      PORT: 3000
      HTTP_MAX_REDIRECTS: 5
      HTTP_TIMEOUT: 5000
      JWT_EXPIRES_IN: 3600
      SITE: SAMPLE-SITE
      PID_PREFIX: PID.SAMPLE.PREFIX
      DOI_PREFIX: DOI.SAMPLE.PREFIX
      METADATA_KEYS_RETURN_LIMIT: 100
      METADATA_PARENT_INSTANCES_RETURN_LIMIT: 100
      # Configure to use keycloak:
      OIDC_ISSUER: "http://keycloak.local:8080/realms/pkce-test"
      OIDC_AUTHORIZATION_URL: "http://keycloak.local:8080/realms/pkce-test"
      OIDC_CLIENT_ID: "scicat"
      OIDC_CLIENT_SECRET: "6kbFdrrHJsMZtI09iFRnR1kgphOyZONh"
      OIDC_CALLBACK_URL: "http://keycloak.local:3000/api/v3/auth/oidc/callback"
      OIDC_SCOPE: 'openid profile email'
      OIDC_SUCCESS_URL: "http://keycloak.local:4200/auth-callback"
      OIDC_ACCESS_GROUPS: "accessgroups"
      OIDC_ADDITIONAL_AUTHORIZED_PARTIES: "scicat-native-normal"
    # command: /bin/sh -c "while true; do sleep 600; done"
    command: npm run start:dev

volumes:
  keycloak_data:
  mongodb_data:
    driver: local
